---
title: "Website Deployment Reflection"
author: "Hala Kishawi, 667176531"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document:
    theme: cosmo
---

## Website Information

**Live Website URL:** https://halakishawi.github.io/Portfolio/**GitHub Repository URL:** https://halakishawi.github.io/Portfolio/
**Project Type:** Individual Portfolio

## Reflection

This project taught me a lot of things. firstly,it taught me how to build a  website using R Markdown, a tool I used to only used for tests and single reports. Learning to connect pages with `_site.yml`  file was a  new skill that took practice. The most challenging part was the deployment process using GitHub Actions. I overcame this doing it over until I stopped getting an error. Successfully seeing my portfolio live online helped me see that I can combine both sites to create my websites.

## Website Overview

My portfolio website features a Home page with my introduction and skills, an About page with my background, education, and contact details, and a Projects page detailing one data analysis project I completed in a finance class, which demonstrates my process and the technical skills I applied.
